language: rust
rust: nightly
os:
  - linux
  - osx
env:
  - ARCH=x86_64
  - ARCH=i686
addons:
  apt:
    packages:
      - gcc-multilib
sudo: false
script: |
  curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash
  pushd support
  cargo test
  popd
  cargo test && cargo test --release
